name: mlflowproject_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6
  - pandas
  - scikit-learn
  - mlflow
  - python-Levenshtein
  - scipy
  - joblib
  - dagshub=0.5.10
  - pip
