name: mlproject_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.6 # Ganti versi python disini
  - pip
  - pandas
  - scikit-learn
  - mlflow
  - python-Levenshtein
  - scipy
  - joblib
  - dagshub=0.5.10
  - pip:
      - dagshub=0.5.10
      - mlflow
      - scikit-learn
      - python-Levenshtein
