name: MLflow CI - Retrain Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6

      - name: Update Conda
        run: |
          conda update -n base -c defaults conda --yes
          conda --version

      - name: Conda Init
        shell: bash
        run: |
          conda init bash && source ~/.bashrc # Load the updated bash configuration

      - name: Clear Conda Cache
        run: |
          conda clean --all --yes

      - name: Set Conda Channel Priority
        run: |
          conda config --set channel_priority strict

      - name: Install dependencies
        run: |
          cd MLProject
          conda env create -f conda.yaml --name mlflowproject_env
          conda activate mlflowproject_env
          conda install -c conda-forge mlflow  # Memastikan mlflow terinstal di environment yang benar
          conda run -n mlflowproject_env pip install -r requirements.txt

      - name: Run MLflow project
        id: mlflow-run
        run: |
          cd MLProject # Make sure you are in the directory before running
          conda activate mlflowproject_env # Pastikan environment diaktifkan
          conda run -n mlflowproject_env mlflow run . > output.txt
          python -c "
          import re
          with open('output.txt', 'r') as f:
              output = f.read()
          match = re.search(r'Run ID: (\w+)', output)
          if match:
              run_id = match.group(1)
              print(f'::set-output name=run_id::{run_id}')
          else:
              print('Run ID not found in output.')
          "

        env:
          MLFLOW_TRACKING_URI: file:./mlruns #Ganti dengan Tracking Server

      - name: Upload Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model
          path: MLProject/mlruns/0/${{ steps.mlflow-run.outputs.run_id }}/artifacts/model

      - name: Commit and push if changed
        run: |
          git config --global user.email "margaretalolalilullita@gmail.com"
          git config --global user.name "margaretalola"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Retrained model (CI)" -a
            git push origin main
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u margaretalola --password-stdin
          conda activate mlflowproject_env # Pastikan environment diaktifkan
          conda run -n mlflowproject_env mlflow models build-docker -m runs:/"${{ steps.mlflow-run.outputs.run_id }}"/model -n margaretalola/course-recommendation-model:latest
          docker push margaretalola/course-recommendation-model:latest
        env:
          DOCKER_USERNAME: margaretalola
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }} # Ganti dengan tracking server URI
