name: MLflow CI - Retrain Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6

      - name: Update Conda
        run: |
          conda update -n base -c defaults conda --yes
          conda --version

      - name: Conda Init
        shell: bash
        run: |
          conda init bash
          source ~/.bashrc

      - name: Clear Conda Cache
        run: conda clean --all --yes

      - name: Set Conda Channel Priority
        run: conda config --set channel_priority strict

      - name: Install dependencies
        run: |
          cd MLProject
          conda env create -f conda.yaml
          conda run -n mlflowproject_env pip install -r requirements.txt
          conda run -n mlflowproject_env pip install mlflow

      - name: Run MLflow project and extract run_id
        id: mlflow-run
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: |
          cd MLProject
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate mlflowproject_env

          echo "Running MLflow project..."
          mlflow run . --env-manager=local --experiment-name Course-Recommendation -P some-param=value > output.txt

          echo "Extracting run_id from logs..."
          RUN_ID=$(grep -oE "Run \(ID '[a-f0-9]+'\)" output.txt | sed -E "s/Run \(ID '([a-f0-9]+)'\)/\1/")
          echo "Run ID: $RUN_ID"

          if [ -z "$RUN_ID" ]; then
            echo "ERROR: run_id not found in mlflow output."
            cat output.txt
            exit 1
          fi

          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Upload Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model
          path: MLProject/models/

      - name: Commit and push if changed
        run: |
          git config --global user.email "margaretalolalilullita@gmail.com"
          git config --global user.name "margaretalola"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git add .
          git diff-index --quiet HEAD || git commit -m "Retrained model (CI)"
          git push origin main

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: margaretalola
        run: |
          echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u $DOCKER_USERNAME --password-stdin
          conda run -n mlflowproject_env mlflow models build-docker \
            -m runs:/${{ steps.mlflow-run.outputs.run_id }}/model \
            -n margaretalola/course-recommendation-model:latest
          docker push margaretalola/course-recommendation-model:latest
