name: MLflow CI - Retrain Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.6

      - name: Clear Conda Cache
        run: |
          conda clean --all --yes

      - name: Set Conda Channel Priority
        run: |
          conda config --set channel_priority strict

      - name: Install dependencies
        run: |
          cd MLProject # Change to the MLProject directory
          conda env create -f conda.yaml # Create conda environment
          conda activate mlflowproject_env # Activate the environment
          pip install -r requirements.txt

      - name: Run MLflow project
        id: mlflow-run
        run: |
          cd MLProject 
          mlflow run .  # Run MLflow project

      - name: Upload Model as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model
          path: MLProject/mlruns/0/*/artifacts/model

      - name: Commit and push if changed
        run: |
          git config --global user.email "margaretalolilullita@gmail.com" 
          git config --global user.name "margaretalola" 
          git commit -m "Retrained model (CI)" -a || echo "No changes to commit"
          git push origin main

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u margaretalola --password-stdin
          mlflow models build-docker -m runs:/"${{ steps.mlflow-run.outputs.run_id }}"/model -n margaretalola/course-recommendation-model:latest
          docker push margaretalola/course-recommendation-model:latest
        env:
          DOCKER_USERNAME: margaretalola
